# This workflow deploys changes to my OCI Autonomous database; mainly to be aligned with local development.

name: Deploy to OCI.

on:
  push:
    branches:
      - main
      - feat/6-cicd

jobs:
  deploy-dev:
    name: 'Deploy to DEV schema.'
    runs-on: ubuntu-latest

    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

    steps:

      - name: Create directory for OCI DB wallet.
        run: mkdir -p /home/runner/work/oci_wallet

      # https://github.com/oracle-actions/run-oci-cli-command/issues/24
      - name: Install OCI CLI.
        id: install-oci-cli
        uses: oracle-actions/run-oci-cli-command@v1.1.1

        with:
          command: 'os ns get'

      - name: Download DB wallet.
        id: generate-wallet
        run: |
          oci db autonomous-database generate-wallet \
            --autonomous-database-id ${{ secrets.OCI_DB_OCID }} \
            --file /home/runner/work/oci_wallet/wallet.zip \
            --password ${{ secrets.DB_WALLET_PASSWORD }}

      # Checkout the repository to the GitHub Actions runner.
      - name: Checkout repository.
        uses: actions/checkout@v4

      - name: list content of current dir
        run: |
          echo $(pwd)
          ls -la
          ls -la /home/runner/work/oci_wallet

    #   - name: Install SQLcl.
    #     uses: gvenzl/setup-oracle-sqlcl@v1
